//! The bridge: `aralo-core` as the native shells see it, generated by UniFFI.
//!
//! Two objects cross the bridge. [`Engine`] is the keystroke path: one call per
//! key, one short lock, no file access. [`Core`] is everything else. They share
//! one [`aralo_core::Runtime`], so a match comes back from `on_key` with its
//! plan already built and the shell never makes a second call while a key is
//! waiting.
//!
//! The library is watched and indexed for as long as the [`Core`] lives. A
//! change, whoever made it, reaches the matcher before it reaches the shell:
//! the next keystroke matches what the folder now says even if the shell has
//! not drawn anything yet.
//!
//! Nothing here may panic: a panic would cross the bridge as a crash in the
//! process that holds the event tap. Locks recover from poisoning instead.
//!
//! Where two locks are held at once the library is taken first and the matcher
//! second, on every thread. The keystroke path takes one at a time, which is
//! what keeps it out of the way of a save.
//!
//! There is no hand-written `unsafe` in this crate. The only `unsafe` is what
//! `uniffi::setup_scaffolding!` generates, which is why this is the one crate
//! that does not forbid it.

use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, MutexGuard, PoisonError, RwLock, RwLockReadGuard};

use aralo_core::compat;
use aralo_core::engine as matcher;
use aralo_core::snippet::{CaseMode, SnippetId, SnippetKind, TriggerMode};
use aralo_core::{
    CompatTable, Draft, ExportOptions, Format, ImportOptions, ImportReport, LibraryChange,
    LibraryListener, MacroPolicy, MatchInfo, Outcome, Query, Runtime, RuntimeOptions, Step,
};

uniffi::setup_scaffolding!();

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum BridgeError {
    #[error("{message}")]
    Library { message: String },
    #[error("{message}")]
    CompatTable { message: String },
    #[error("{message}")]
    Import { message: String },
}

impl From<aralo_core::CoreError> for BridgeError {
    fn from(error: aralo_core::CoreError) -> Self {
        BridgeError::Library {
            message: error.to_string(),
        }
    }
}

/// A key as the shell saw it, after the keyboard layout and dead keys.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum KeyInput {
    /// A key that produced exactly one Unicode scalar. It crosses the bridge as
    /// a number so that no keystroke ever sits in a heap-allocated string. A
    /// key that produced several is not reported; the shell calls
    /// `reset(UnmappableInput)`. A key that produced none (a dead key on its
    /// own) is not reported at all.
    Char {
        scalar: u32,
    },
    Backspace,
    /// The platform's undo shortcut.
    Undo,
}

/// What the shell does with the key it just reported.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Enum)]
pub enum KeyAction {
    /// Let the key through.
    Pass,
    /// Swallow the key if `consume`, run the steps in order the way `profile`
    /// says, then call `expansion_done` when `undo_delete_count` is present.
    Expand {
        snippet_id: String,
        consume: bool,
        steps: Vec<PlanStep>,
        undo_delete_count: Option<u32>,
        profile: InjectionProfile,
    },
    /// Swallow the key, take the expansion back the way `profile` says
    /// (`delete_count` Backspaces, or one undo shortcut), type `retype`.
    UndoExpansion {
        delete_count: u32,
        retype: String,
        method: InsertMethod,
        profile: InjectionProfile,
    },
}

/// How to insert, delete and undo in the app that has the keyboard; one row of
/// the compatibility table (`data/compat/apps.toml`). The shell follows it and
/// chooses nothing itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]
pub struct InjectionProfile {
    pub insert: InsertChoice,
    /// The longest text `Auto` still types, in UTF-16 units.
    pub typing_limit: u32,
    /// Pause after every synthetic key.
    pub key_delay_ms: u32,
    /// How long the app gets to read the pasteboard before it is restored.
    pub paste_settle_ms: u32,
    pub undo: UndoStyle,
    pub delete: DeleteStrategy,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum InsertChoice {
    /// Type short single-line text, paste the rest.
    Auto,
    /// Always type. A line break is a Return key.
    Type,
    /// Always paste.
    Paste,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum UndoStyle {
    /// A pasted expansion is undone with one undo shortcut.
    Native,
    /// Every expansion is undone with Backspace.
    Backspace,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum DeleteStrategy {
    /// One Backspace per character.
    Backspace,
    /// Shift+Left over the characters, then one Backspace.
    Select,
}

/// One step of an expansion plan; see `docs/format/expansion-plan.md`.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Enum)]
pub enum PlanStep {
    Delete { count: u32 },
    InsertText { text: String },
    InsertRich { html: String, plain: String },
    KeyPress { key: PlanKey },
    Delay { millis: u32 },
    MoveCursor { graphemes: u32, select: bool },
}

/// One app the compatibility table names, with its row resolved.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct CompatApp {
    pub name: String,
    pub bundle_id: String,
    pub profile: InjectionProfile,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum PlanKey {
    Return,
    Tab,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum InsertMethod {
    Typed,
    Pasted,
}

/// Why the shell is clearing the buffer. Every reason zeroes it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ResetReason {
    MouseDown,
    Navigation,
    Shortcut,
    AppSwitch,
    FocusChange,
    SecureInput,
    InputMethod,
    UnmappableInput,
    Manual,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SnippetSummary {
    pub id: String,
    pub label: String,
    pub abbreviations: Vec<String>,
    /// Folder names from the library root down to the snippet's group.
    pub group: Vec<String>,
    /// Path from the library root.
    pub path: String,
    pub enabled: bool,
    /// The start of the body, for a list row.
    pub preview: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum DiagnosticLevel {
    Error,
    Warning,
    Note,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct LibraryDiagnostic {
    /// Path from the library root.
    pub path: String,
    pub level: DiagnosticLevel,
    pub message: String,
}

/// The library both objects share, running: watched, indexed, and read under a
/// lock the keystroke path only ever holds for the length of one lookup.
struct Shared {
    runtime: Runtime,
    compat: RwLock<CompatTable>,
}

impl Shared {
    fn compat(&self) -> RwLockReadGuard<'_, CompatTable> {
        self.compat.read().unwrap_or_else(PoisonError::into_inner)
    }
}

/// What the runtime tells the bridge, and what the bridge does about it: the
/// matcher gets the new snapshot, then the shell is told.
struct Events {
    matcher: Arc<Mutex<matcher::Engine>>,
    shell: Option<Arc<dyn CoreEvents>>,
}

impl LibraryListener for Events {
    fn changed(&self, change: LibraryChange, library: &aralo_core::Core) {
        // The snapshot first, and whether or not anyone is listening: a shell
        // that shows nothing still expands what the folder says.
        if !matches!(change, LibraryChange::Indexed { .. }) {
            self.matcher
                .lock()
                .unwrap_or_else(PoisonError::into_inner)
                .set_snapshot(library.snapshot());
        }
        if let Some(shell) = &self.shell {
            shell.library_changed(change.into());
        }
    }
}

/// The app that receives keys, and its row of the compatibility table. Looked
/// up when the app changes, so a match only has to copy it.
struct FrontApp {
    bundle_id: String,
    profile: compat::InjectionProfile,
}

/// The keystroke path.
#[derive(uniffi::Object)]
pub struct Engine {
    /// Shared with [`Events`], which swaps the snapshot in when the library
    /// changes. The tap thread and the watch thread both take this lock; both
    /// hold it for one call.
    matcher: Arc<Mutex<matcher::Engine>>,
    front_app: Mutex<FrontApp>,
    shared: Arc<Shared>,
}

impl std::fmt::Debug for Engine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Engine").finish_non_exhaustive()
    }
}

impl Engine {
    fn matcher(&self) -> MutexGuard<'_, matcher::Engine> {
        self.matcher.lock().unwrap_or_else(PoisonError::into_inner)
    }

    fn front_app(&self) -> MutexGuard<'_, FrontApp> {
        self.front_app
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
    }

    /// Not taken on the way in: only a match or an undo needs it.
    fn profile(&self) -> InjectionProfile {
        self.front_app().profile.into()
    }

    /// Looks the front app up again, after the table changed.
    fn refresh_profile(&self) {
        let mut front_app = self.front_app();
        front_app.profile = self.shared.compat().profile_for(&front_app.bundle_id);
    }
}

#[uniffi::export]
impl Engine {
    pub fn on_key(&self, key: KeyInput) -> KeyAction {
        let event = match key {
            KeyInput::Char { scalar } => match char::from_u32(scalar) {
                Some(c) => matcher::KeyEvent::Char(c),
                None => {
                    self.matcher().reset(matcher::ResetReason::UnmappableInput);
                    return KeyAction::Pass;
                }
            },
            KeyInput::Backspace => matcher::KeyEvent::Backspace,
            KeyInput::Undo => matcher::KeyEvent::Undo,
        };
        // The engine lock is released before the plan is built.
        let verdict = self.matcher().on_key(event);
        match verdict {
            matcher::KeyVerdict::Pass => KeyAction::Pass,
            matcher::KeyVerdict::Match {
                snippet_id,
                delete_count,
                consume,
                case,
                trailing,
            } => {
                let expansion = self.shared.runtime.read(|core| {
                    core.expand(MatchInfo {
                        snippet_id,
                        delete_count,
                        case,
                        trailing,
                    })
                });
                match expansion {
                    Some(expansion) => KeyAction::Expand {
                        snippet_id: SnippetId::from_u128(snippet_id.0).to_string(),
                        consume,
                        steps: expansion
                            .plan
                            .steps
                            .into_iter()
                            .map(PlanStep::from)
                            .collect(),
                        undo_delete_count: expansion.undo_delete_count,
                        profile: self.profile(),
                    },
                    // The snippet went away between the snapshot and now.
                    None => KeyAction::Pass,
                }
            }
            matcher::KeyVerdict::UndoLast {
                delete_count,
                retype,
                method,
            } => KeyAction::UndoExpansion {
                delete_count,
                retype,
                method: match method {
                    matcher::InsertMethod::Typed => InsertMethod::Typed,
                    matcher::InsertMethod::Pasted => InsertMethod::Pasted,
                },
                profile: self.profile(),
            },
        }
    }

    /// Arms undo for the expansion that `on_key` just returned, and counts it
    /// towards the recents list. The count is queued, not written here: this is
    /// called the moment the text lands, and that thread waits for nothing.
    pub fn expansion_done(&self, snippet_id: String, delete_count: u32, method: InsertMethod) {
        let Ok(id) = snippet_id.parse::<SnippetId>() else {
            return;
        };
        self.shared.runtime.record_expansion(id);
        self.matcher().expansion_done(matcher::ExpansionRecord {
            snippet_id: matcher::SnippetId(id.as_u128()),
            delete_count,
            method: match method {
                InsertMethod::Typed => matcher::InsertMethod::Typed,
                InsertMethod::Pasted => matcher::InsertMethod::Pasted,
            },
        });
    }

    pub fn reset(&self, reason: ResetReason) {
        self.matcher().reset(match reason {
            ResetReason::MouseDown => matcher::ResetReason::MouseDown,
            ResetReason::Navigation => matcher::ResetReason::Navigation,
            ResetReason::Shortcut => matcher::ResetReason::Shortcut,
            ResetReason::AppSwitch => matcher::ResetReason::AppSwitch,
            ResetReason::FocusChange => matcher::ResetReason::FocusChange,
            ResetReason::SecureInput => matcher::ResetReason::SecureInput,
            ResetReason::InputMethod => matcher::ResetReason::InputMethod,
            ResetReason::UnmappableInput => matcher::ResetReason::UnmappableInput,
            ResetReason::Manual => matcher::ResetReason::Manual,
        });
    }

    /// The bundle ID of the app that now receives keys.
    pub fn set_front_app(&self, bundle_id: String) {
        self.matcher().set_front_app(&bundle_id);
        let profile = self.shared.compat().profile_for(&bundle_id);
        *self.front_app() = FrontApp { bundle_id, profile };
    }

    /// How text goes into the app that has the keyboard now.
    pub fn injection_profile(&self) -> InjectionProfile {
        self.profile()
    }

    pub fn set_paused(&self, paused: bool) {
        self.matcher().set_paused(paused);
    }

    pub fn is_paused(&self) -> bool {
        self.matcher().is_paused()
    }

    /// Apps the user excluded. The built-in presets (password managers) stay
    /// excluded as well: the engine's own call replaces the whole list, and a
    /// shell that forgot to pass the presets along would silently drop them.
    pub fn set_excluded_apps(&self, mut bundle_ids: Vec<String>) {
        bundle_ids.extend(excluded_app_presets());
        self.matcher().set_excluded_apps(bundle_ids);
    }

    /// True when the buffer holds nothing. For the privacy self-test.
    pub fn holds_no_keystrokes(&self) -> bool {
        self.matcher().holds_no_keystrokes()
    }
}

/// The open library.
#[derive(uniffi::Object)]
pub struct Core {
    shared: Arc<Shared>,
    engine: Arc<Engine>,
}

impl std::fmt::Debug for Core {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Core").finish_non_exhaustive()
    }
}

#[uniffi::export]
impl Core {
    /// Opens the library folder, creating it (with the starter snippets) when
    /// it does not exist yet, and starts watching and indexing it.
    ///
    /// `cache` is the folder Aralo may keep rebuildable files in — the search
    /// index, and nothing the user would miss. The shell passes the one its
    /// platform gives it, because a sandboxed app's is not where an unsandboxed
    /// one's is; nothing means work it out, which is what the command line
    /// does. A cache that will not open costs recents and usage counts and
    /// nothing else: `index_problem` then says why.
    ///
    /// `events` is how the shell hears about changes it did not make. A shell
    /// that passes none still expands: the matcher is brought up to date
    /// either way.
    #[uniffi::constructor]
    pub fn open_library(
        path: String,
        cache: Option<String>,
        events: Option<Arc<dyn CoreEvents>>,
    ) -> Result<Arc<Self>, BridgeError> {
        let root = PathBuf::from(path);
        let library = aralo_core::Core::open(&root)?;
        let matcher = Arc::new(Mutex::new(library.engine()));
        let listener = Arc::new(Events {
            matcher: Arc::clone(&matcher),
            shell: events,
        });
        let options = RuntimeOptions {
            index: cache.map(|cache| aralo_core::state::index_in(Path::new(&cache), &root)),
            ..RuntimeOptions::default()
        };
        let runtime = Runtime::with_core(library, options, listener)?;
        let compat = CompatTable::bundled();
        let front_app = FrontApp {
            bundle_id: String::new(),
            profile: compat.defaults(),
        };
        let shared = Arc::new(Shared {
            runtime,
            compat: RwLock::new(compat),
        });
        let engine = Arc::new(Engine {
            matcher,
            front_app: Mutex::new(front_app),
            shared: Arc::clone(&shared),
        });
        Ok(Arc::new(Self { shared, engine }))
    }

    /// The engine for this library. There is one; every call returns it.
    pub fn engine(&self) -> Arc<Engine> {
        Arc::clone(&self.engine)
    }

    /// Reads the folder again. The engine gets the new snapshot and the shell
    /// hears `Reloaded`; on failure the library that was loaded stays in use.
    ///
    /// Nothing has to call this to see an outside change: the watch does. It is
    /// for a folder that arrived while Aralo was not looking, and for a user
    /// who would rather be sure.
    pub fn reload(&self) -> Result<(), BridgeError> {
        Ok(self.shared.runtime.reload()?)
    }

    /// Replaces the built-in compatibility table with the file at `path`, for
    /// trying an app's settings without rebuilding the core. A file that does
    /// not parse changes nothing.
    pub fn load_compat_table(&self, path: String) -> Result<(), BridgeError> {
        let table = read_compat_table(&path)?;
        *self
            .shared
            .compat
            .write()
            .unwrap_or_else(PoisonError::into_inner) = table;
        self.engine.refresh_profile();
        Ok(())
    }

    pub fn library_path(&self) -> String {
        self.shared.runtime.root().to_string_lossy().into_owned()
    }

    pub fn snippets(&self) -> Vec<SnippetSummary> {
        self.shared
            .runtime
            .read(|core| core.snippets().iter().map(summarise).collect())
    }

    pub fn diagnostics(&self) -> Vec<LibraryDiagnostic> {
        self.shared.runtime.read(|core| {
            core.diagnostics()
                .map(|diagnostic| {
                    let (level, message) = describe(&diagnostic.issue);
                    LibraryDiagnostic {
                        path: diagnostic.path.to_string_lossy().into_owned(),
                        level,
                        message,
                    }
                })
                .collect()
        })
    }
}

/// The editor: everything that changes the folder, and everything the editor
/// needs to show before it does.
///
/// Every call here writes files and reads the folder again, so what comes back
/// from `snippets()` next is what a text editor would show. A `Core` with an
/// `events` listener hears `Edited` for each one.
#[uniffi::export]
impl Core {
    /// Every group in the library, root first, then in folder order.
    pub fn groups(&self) -> Vec<GroupSummary> {
        self.shared.runtime.read(|core| {
            core.library()
                .groups()
                .iter()
                .map(|group| GroupSummary {
                    path: group.path.clone(),
                    name: group.name.clone(),
                    colour: group.colour.clone(),
                    icon: group.icon.clone(),
                    enabled: group.enabled,
                    snippets: group.snippets as u32,
                })
                .collect()
        })
    }

    /// One snippet, with everything the editor puts on screen. `None` when
    /// there is no snippet with that ID.
    pub fn snippet(&self, id: String) -> Option<SnippetDetail> {
        let id = id.parse::<SnippetId>().ok()?;
        self.shared.runtime.read(|core| {
            let snippet = core.library().snippet(id)?;
            Some(SnippetDetail {
                id: snippet.id.to_string(),
                path: snippet.path.to_string_lossy().into_owned(),
                group: snippet.group.clone(),
                draft: SnippetDraft::from(&Draft::of(snippet)),
                resolved: ResolvedSettings {
                    trigger: match snippet.settings.trigger {
                        matcher::Trigger::Immediate => Trigger::Immediate,
                        matcher::Trigger::Delimiter => Trigger::Delimiter,
                    },
                    case: match snippet.settings.case {
                        matcher::CaseMode::Exact => CaseStyle::Exact,
                        matcher::CaseMode::Ignore => CaseStyle::Ignore,
                        matcher::CaseMode::Adaptive => CaseStyle::Adaptive,
                    },
                    whole_word: snippet.settings.whole_word,
                    keep_delimiter: snippet.settings.keep_delimiter,
                    enabled: snippet.settings.enabled,
                },
                preview: core.preview(id).unwrap_or_default(),
            })
        })
    }

    /// Writes a new snippet into `group` and returns its ID. An empty group is
    /// the library root.
    pub fn create_snippet(
        &self,
        group: Vec<String>,
        draft: SnippetDraft,
    ) -> Result<String, BridgeError> {
        let draft = Draft::from(&draft);
        let id = self
            .shared
            .runtime
            .edit(|core| core.create_snippet(&group, &draft))?;
        Ok(id.to_string())
    }

    /// Writes `draft` over the snippet `id`, in the file it is already in, and
    /// returns its ID afterwards. That differs from `id` only for a
    /// hand-written file that carried none until now.
    pub fn save_snippet(&self, id: String, draft: SnippetDraft) -> Result<String, BridgeError> {
        let id = snippet_id(&id)?;
        let draft = Draft::from(&draft);
        let saved = self
            .shared
            .runtime
            .edit(|core| core.save_snippet(id, &draft))?;
        Ok(saved.to_string())
    }

    /// Removes a snippet's file. It is unlinked, not put in the trash: a shell
    /// that would rather the user could get it back moves the file itself,
    /// using `snippet()`'s path, and calls `reload()`.
    pub fn delete_snippet(&self, id: String) -> Result<(), BridgeError> {
        let id = snippet_id(&id)?;
        self.shared.runtime.edit(|core| core.delete_snippet(id))?;
        Ok(())
    }

    /// Moves a snippet into another group, keeping its ID.
    pub fn move_snippet(&self, id: String, group: Vec<String>) -> Result<(), BridgeError> {
        let id = snippet_id(&id)?;
        self.shared
            .runtime
            .edit(|core| core.move_snippet(id, &group))?;
        Ok(())
    }

    pub fn set_snippet_enabled(&self, id: String, enabled: bool) -> Result<(), BridgeError> {
        let id = snippet_id(&id)?;
        self.shared
            .runtime
            .edit(|core| core.set_snippet_enabled(id, enabled))?;
        Ok(())
    }

    /// Creates an empty group: one folder, and no `_group.yaml` until
    /// something in it is set.
    pub fn create_group(&self, group: Vec<String>) -> Result<(), BridgeError> {
        self.shared.runtime.edit(|core| core.create_group(&group))?;
        Ok(())
    }

    /// Renames a group's folder and returns its new path from the root.
    pub fn rename_group(
        &self,
        group: Vec<String>,
        name: String,
    ) -> Result<Vec<String>, BridgeError> {
        Ok(self
            .shared
            .runtime
            .edit(|core| core.rename_group(&group, &name))?)
    }

    /// Moves a group, and everything in it, inside `into`. An empty `into` is
    /// the library root. Returns its new path.
    pub fn move_group(
        &self,
        group: Vec<String>,
        into: Vec<String>,
    ) -> Result<Vec<String>, BridgeError> {
        Ok(self
            .shared
            .runtime
            .edit(|core| core.move_group(&group, &into))?)
    }

    /// Removes a group's folder and everything in it, and returns the paths
    /// that went. `group_contents` says how much there is, so a shell can ask
    /// the user first.
    pub fn delete_group(&self, group: Vec<String>) -> Result<Vec<String>, BridgeError> {
        let removed = self.shared.runtime.edit(|core| core.delete_group(&group))?;
        Ok(removed
            .iter()
            .map(|path| path.to_string_lossy().into_owned())
            .collect())
    }

    /// Switches a group on or off. Off is sticky: nothing inside it expands,
    /// whatever a group further down says.
    pub fn set_group_enabled(&self, group: Vec<String>, enabled: bool) -> Result<(), BridgeError> {
        self.shared
            .runtime
            .edit(|core| core.set_group_enabled(&group, enabled))?;
        Ok(())
    }

    /// The colour and icon a group is shown with. `None` clears one.
    pub fn set_group_appearance(
        &self,
        group: Vec<String>,
        colour: Option<String>,
        icon: Option<String>,
    ) -> Result<(), BridgeError> {
        self.shared.runtime.edit(|core| {
            core.edit_group(&group, |file| {
                file.colour = colour;
                file.icon = icon;
            })
        })?;
        Ok(())
    }

    /// How many snippets a group holds, counting the groups inside it.
    pub fn group_contents(&self, group: Vec<String>) -> u32 {
        self.shared.runtime.read(|core| core.group_contents(&group)) as u32
    }

    /// What the editor should say about a draft before it is saved: blank and
    /// repeated abbreviations, and ones another snippet already answers to.
    /// None of them stops a save.
    ///
    /// `editing` is the snippet on screen, so that its own abbreviations are
    /// not reported as taken by itself. Pass nothing for a new snippet.
    pub fn check_draft(&self, draft: SnippetDraft, editing: Option<String>) -> Vec<DraftProblem> {
        let draft = Draft::from(&draft);
        let editing = editing.and_then(|id| id.parse::<SnippetId>().ok());
        self.shared.runtime.read(|core| {
            core.check_draft(&draft, editing)
                .into_iter()
                .map(DraftProblem::from)
                .collect()
        })
    }

    /// An abbreviation for a snippet called `label` that nothing answers to
    /// yet, for the editor to fill the field with. Empty when the label has no
    /// letters in it.
    pub fn suggest_abbreviation(&self, label: String) -> String {
        self.shared
            .runtime
            .read(|core| core.suggest_abbreviation(&label))
    }

    /// Every snippet matching `query`, best first. An empty query text is the
    /// whole library in list order, so a list and its search box are one call,
    /// and `group` narrows it to whatever the editor's sidebar has selected.
    pub fn search(&self, query: SearchQuery) -> Vec<SearchResult> {
        let mut search = Query::new(query.text);
        search.group = query.group;
        search.tag = query.tag;
        search.enabled_only = query.enabled_only;
        if query.limit > 0 {
            search.limit = Some(query.limit as usize);
        }
        self.shared.runtime.read(|core| {
            core.search(&search)
                .into_iter()
                .map(SearchResult::from)
                .collect()
        })
    }

    /// What a snippet expands to, for the editor's preview pane.
    pub fn preview(&self, id: String) -> Option<String> {
        let id = id.parse::<SnippetId>().ok()?;
        self.shared.runtime.read(|core| core.preview(id))
    }

    /// What a body that is still being typed would expand to. The file is not
    /// consulted, so the editor's preview keeps up with the keystroke.
    pub fn preview_draft(&self, body: String) -> String {
        aralo_core::Core::preview_body(&body)
    }

    /// The snippets expanded most recently, most recent first. Empty when
    /// there is no index; `index_problem` says why.
    pub fn recents(&self, limit: u32) -> Vec<String> {
        self.shared
            .runtime
            .recents(limit as usize)
            .unwrap_or_default()
            .into_iter()
            .map(|recent| recent.id.to_string())
            .collect()
    }

    /// Why there is no search index, when there is none. Recents and usage
    /// counts are what is lost; everything else works without it.
    pub fn index_problem(&self) -> Option<String> {
        self.shared.runtime.index_error().map(str::to_owned)
    }

    /// Reads a file from another expander into the library. A dry run reports
    /// what would happen and writes nothing.
    ///
    /// The report is the answer, not a side effect: an import does not fail
    /// because one snippet did not convert, and the shell shows the report.
    pub fn import(
        &self,
        source: String,
        options: ImportSettings,
    ) -> Result<ImportSummary, BridgeError> {
        let format = match options.format {
            Some(name) => Some(parse_format(&name)?),
            None => None,
        };
        let settings = ImportOptions {
            format,
            into: options.into_group,
            macros: match options.macros {
                MacroHandling::Auto => MacroPolicy::Auto,
                MacroHandling::Convert => MacroPolicy::Convert,
                MacroHandling::Literal => MacroPolicy::Literal,
                MacroHandling::Template => MacroPolicy::Template,
            },
            dry_run: options.dry_run,
        };
        let source = PathBuf::from(source);
        let report = self
            .shared
            .runtime
            .edit(|core| core.import(&source, &settings))?;
        Ok(ImportSummary::from(&report))
    }

    /// The library, or one group of it, as the bytes of an interchange file.
    /// `format` is one of `csv`, `json` or `yaml`.
    pub fn export(&self, format: String, group: Vec<String>) -> Result<Vec<u8>, BridgeError> {
        let options = ExportOptions {
            format: parse_format(&format)?,
            group,
        };
        Ok(self.shared.runtime.read(|core| core.export(&options))?)
    }
}

/// What the shell is told when the library changes underneath it.
///
/// Called on a background thread, with the library read-locked. Hand the event
/// to the main thread and return: the watch reports nothing else until this
/// comes back, and calling back into `Core` from inside it would wait for a
/// lock this call is holding.
#[uniffi::export(with_foreign)]
pub trait CoreEvents: Send + Sync {
    fn library_changed(&self, event: LibraryEvent);
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Enum)]
pub enum LibraryEvent {
    /// Something outside Aralo changed the folder and it has been read again.
    /// The paths are relative to the library root.
    Outside { paths: Vec<String> },
    /// Aralo changed the folder, through one of the editing calls.
    Edited,
    /// The folder was read again because `reload` asked for it.
    Reloaded,
    /// The folder changed and reading it failed. The library in memory is the
    /// last one that loaded, and expansion carries on with it.
    Failed { message: String },
    /// The search index caught up with the library.
    Indexed {
        added: u32,
        updated: u32,
        removed: u32,
    },
}

/// A snippet's fields as a person edits them. `None` means "inherit from the
/// group", which is not the same as the value the group resolves to today.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct SnippetDraft {
    pub label: String,
    pub abbreviations: Vec<String>,
    pub body: String,
    pub tags: Vec<String>,
    pub kind: SnippetType,
    pub trigger: Option<Trigger>,
    pub case: Option<CaseStyle>,
    /// Expand only after a non-word character.
    pub whole_word: Option<bool>,
    /// Re-insert the delimiter that triggered the expansion.
    pub keep_delimiter: Option<bool>,
    pub enabled: Option<bool>,
}

/// One snippet as the editor shows it.
#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct SnippetDetail {
    pub id: String,
    /// Path from the library root.
    pub path: String,
    pub group: Vec<String>,
    pub draft: SnippetDraft,
    /// What the draft's `None`s come to once the groups above it are applied.
    pub resolved: ResolvedSettings,
    /// What typing the abbreviation would produce.
    pub preview: String,
}

/// How a snippet behaves with every level of inheritance applied.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]
pub struct ResolvedSettings {
    pub trigger: Trigger,
    pub case: CaseStyle,
    pub whole_word: bool,
    pub keep_delimiter: bool,
    /// False when the snippet or any group above it is switched off.
    pub enabled: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum SnippetType {
    Text,
    Rich,
    Command,
    Prompt,
    Script,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum Trigger {
    /// Expand the moment the abbreviation is complete.
    Immediate,
    /// Expand when a delimiter follows it.
    Delimiter,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum CaseStyle {
    /// Only an exact match expands.
    Exact,
    /// Case is ignored, and the snippet expands as it is written.
    Ignore,
    /// Case is ignored, and the expansion follows how it was typed.
    Adaptive,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct GroupSummary {
    /// Folder names from the library root down. Empty for the root itself.
    pub path: Vec<String>,
    pub name: String,
    pub colour: Option<String>,
    pub icon: Option<String>,
    pub enabled: bool,
    /// Snippets directly in this group, not counting its sub-groups.
    pub snippets: u32,
}

/// Something the editor should say about a draft. None of these stops a save.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct DraftProblem {
    /// Which abbreviation it is about, when it is about one.
    pub abbreviation: Option<String>,
    pub message: String,
    /// The snippet that already answers to this abbreviation, if that is the
    /// problem. The editor offers to show it.
    pub conflicts_with: Option<String>,
}

/// What the snippet list is asking for: the search box, and the filters the
/// sidebar sets. Every field empty is the whole library in list order.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SearchQuery {
    /// What the user typed. Empty matches everything.
    pub text: String,
    /// Only snippets in this group or in a group inside it. `None` is the
    /// whole library; an empty path is the root, which is the same thing.
    pub group: Option<Vec<String>>,
    /// Only snippets carrying this tag, compared without case.
    pub tag: Option<String>,
    /// Leave out snippets that are switched off, here or by a group above them.
    pub enabled_only: bool,
    /// At most this many hits, after ranking. Zero is no limit.
    pub limit: u32,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SearchResult {
    pub id: String,
    pub name: String,
    pub abbreviations: Vec<String>,
    pub group: Vec<String>,
    pub enabled: bool,
    /// Which field matched: the row shows this text with `matched` highlighted.
    pub field: SearchField,
    pub text: String,
    /// Character offsets into `text` that matched, in order.
    pub matched: Vec<u32>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum SearchField {
    Abbreviation,
    Label,
    Body,
    Tag,
    Group,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ImportSettings {
    /// `textexpander`, `csv`, `json` or `yaml`. Nothing asks Aralo to work it
    /// out from the file.
    pub format: Option<String>,
    /// Put everything under this group, above whatever group the source gives.
    pub into_group: Vec<String>,
    pub macros: MacroHandling,
    /// Work out what would happen and write nothing.
    pub dry_run: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum MacroHandling {
    /// Convert the source's macros where the body plainly carries them.
    Auto,
    /// Convert, even where the macros are only a maybe.
    Convert,
    /// Never convert: the body is literal text.
    Literal,
    /// The body is an Aralo template already.
    Template,
}

#[derive(Debug, Clone, PartialEq, uniffi::Record)]
pub struct ImportSummary {
    pub format: String,
    pub dry_run: bool,
    pub total: u32,
    /// Imported, or that would have been.
    pub imported: u32,
    /// Imported, and expands, but something in it needs a human.
    pub needs_edit: u32,
    pub skipped: u32,
    /// The share that converts with no manual edit, from 0 to 1.
    pub fidelity: f64,
    pub entries: Vec<ImportedSnippet>,
    /// The report as the command line prints it, for a window that shows it.
    pub report: String,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct ImportedSnippet {
    pub label: String,
    pub abbreviations: Vec<String>,
    pub group: Vec<String>,
    /// Path from the library root, when one was written.
    pub path: Option<String>,
    pub outcome: ImportOutcome,
    pub notes: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ImportOutcome {
    /// Imported with nothing lost.
    Clean,
    /// Imported, and it will expand, but the notes say what needs a human.
    NeedsEdit,
    /// Not imported.
    Skipped,
}

const PREVIEW_CHARS: usize = 120;

/// The version of the Rust core, for the About window and bug reports.
#[uniffi::export]
pub fn core_version() -> String {
    env!("CARGO_PKG_VERSION").to_owned()
}

/// Apps Aralo stays out of without being told to, for the settings window.
#[uniffi::export]
pub fn excluded_app_presets() -> Vec<String> {
    matcher::EXCLUDED_APP_PRESETS
        .iter()
        .map(|id| (*id).to_owned())
        .collect()
}

/// The apps a compatibility table names, in file order: the table built into
/// the core, or the file at `path`. The injection matrix walks this list, so
/// it tests the apps the table makes claims about.
#[uniffi::export]
pub fn compat_apps(path: Option<String>) -> Result<Vec<CompatApp>, BridgeError> {
    let table = match path {
        Some(path) => read_compat_table(&path)?,
        None => CompatTable::bundled(),
    };
    Ok(table
        .apps()
        .iter()
        .map(|app| CompatApp {
            name: app.name.clone(),
            bundle_id: app.bundle_id.clone(),
            profile: app.profile.into(),
        })
        .collect())
}

fn read_compat_table(path: &str) -> Result<CompatTable, BridgeError> {
    let text = std::fs::read_to_string(path).map_err(|error| BridgeError::CompatTable {
        message: format!("cannot read {path}: {error}"),
    })?;
    CompatTable::parse(&text).map_err(|error| BridgeError::CompatTable {
        message: format!("{path}: {error}"),
    })
}

impl From<compat::InjectionProfile> for InjectionProfile {
    fn from(profile: compat::InjectionProfile) -> Self {
        Self {
            insert: match profile.insert {
                compat::InsertChoice::Auto => InsertChoice::Auto,
                compat::InsertChoice::Type => InsertChoice::Type,
                compat::InsertChoice::Paste => InsertChoice::Paste,
            },
            typing_limit: profile.typing_limit,
            key_delay_ms: profile.key_delay_ms,
            paste_settle_ms: profile.paste_settle_ms,
            undo: match profile.undo {
                compat::UndoStyle::Native => UndoStyle::Native,
                compat::UndoStyle::Backspace => UndoStyle::Backspace,
            },
            delete: match profile.delete {
                compat::DeleteStrategy::Backspace => DeleteStrategy::Backspace,
                compat::DeleteStrategy::Select => DeleteStrategy::Select,
            },
        }
    }
}

impl From<Step> for PlanStep {
    fn from(step: Step) -> Self {
        match step {
            Step::Delete { count } => PlanStep::Delete { count },
            Step::InsertText { text } => PlanStep::InsertText { text },
            Step::InsertRich { html, plain } => PlanStep::InsertRich { html, plain },
            Step::KeyPress { key } => PlanStep::KeyPress {
                key: match key {
                    aralo_core::Key::Return => PlanKey::Return,
                    aralo_core::Key::Tab => PlanKey::Tab,
                },
            },
            Step::Delay { millis } => PlanStep::Delay { millis },
            Step::MoveCursor { graphemes, select } => PlanStep::MoveCursor { graphemes, select },
        }
    }
}

fn summarise(snippet: &aralo_core::LoadedSnippet) -> SnippetSummary {
    SnippetSummary {
        id: snippet.id.to_string(),
        label: snippet.file.front.label.clone(),
        abbreviations: snippet.file.front.abbr.clone(),
        group: snippet.group.clone(),
        path: snippet.path.to_string_lossy().into_owned(),
        enabled: snippet.settings.enabled,
        preview: snippet.file.body.chars().take(PREVIEW_CHARS).collect(),
    }
}

/// An ID the shell handed back. Anything but one Aralo gave it is a bug in the
/// shell, so it reads as "no such snippet" rather than as a crash.
fn snippet_id(text: &str) -> Result<SnippetId, BridgeError> {
    text.parse::<SnippetId>().map_err(|_| BridgeError::Library {
        message: format!("no snippet with the id {text} is in the library"),
    })
}

fn parse_format(name: &str) -> Result<Format, BridgeError> {
    name.parse::<Format>().map_err(|error| BridgeError::Import {
        message: error.to_string(),
    })
}

impl From<LibraryChange> for LibraryEvent {
    fn from(change: LibraryChange) -> Self {
        match change {
            LibraryChange::Outside { paths } => LibraryEvent::Outside {
                paths: paths
                    .iter()
                    .map(|path| path.to_string_lossy().into_owned())
                    .collect(),
            },
            LibraryChange::Edited => LibraryEvent::Edited,
            LibraryChange::Reloaded => LibraryEvent::Reloaded,
            LibraryChange::Failed { message } => LibraryEvent::Failed { message },
            LibraryChange::Indexed {
                added,
                updated,
                removed,
            } => LibraryEvent::Indexed {
                added: added as u32,
                updated: updated as u32,
                removed: removed as u32,
            },
        }
    }
}

impl From<&Draft> for SnippetDraft {
    fn from(draft: &Draft) -> Self {
        Self {
            label: draft.label.clone(),
            abbreviations: draft.abbr.clone(),
            body: draft.body.clone(),
            tags: draft.tags.clone(),
            kind: draft.kind.into(),
            trigger: draft.trigger.map(Trigger::from),
            case: draft.case.map(CaseStyle::from),
            whole_word: draft.word,
            keep_delimiter: draft.keep_delimiter,
            enabled: draft.enabled,
        }
    }
}

impl From<&SnippetDraft> for Draft {
    fn from(draft: &SnippetDraft) -> Self {
        Self {
            label: draft.label.clone(),
            abbr: draft.abbreviations.clone(),
            body: draft.body.clone(),
            tags: draft.tags.clone(),
            kind: draft.kind.into(),
            trigger: draft.trigger.map(TriggerMode::from),
            case: draft.case.map(CaseMode::from),
            word: draft.whole_word,
            keep_delimiter: draft.keep_delimiter,
            enabled: draft.enabled,
        }
    }
}

impl From<SnippetKind> for SnippetType {
    fn from(kind: SnippetKind) -> Self {
        match kind {
            SnippetKind::Text => SnippetType::Text,
            SnippetKind::Rich => SnippetType::Rich,
            SnippetKind::Command => SnippetType::Command,
            SnippetKind::Prompt => SnippetType::Prompt,
            SnippetKind::Script => SnippetType::Script,
        }
    }
}

impl From<SnippetType> for SnippetKind {
    fn from(kind: SnippetType) -> Self {
        match kind {
            SnippetType::Text => SnippetKind::Text,
            SnippetType::Rich => SnippetKind::Rich,
            SnippetType::Command => SnippetKind::Command,
            SnippetType::Prompt => SnippetKind::Prompt,
            SnippetType::Script => SnippetKind::Script,
        }
    }
}

impl From<TriggerMode> for Trigger {
    fn from(trigger: TriggerMode) -> Self {
        match trigger {
            TriggerMode::Immediate => Trigger::Immediate,
            TriggerMode::Delimiter => Trigger::Delimiter,
        }
    }
}

impl From<Trigger> for TriggerMode {
    fn from(trigger: Trigger) -> Self {
        match trigger {
            Trigger::Immediate => TriggerMode::Immediate,
            Trigger::Delimiter => TriggerMode::Delimiter,
        }
    }
}

impl From<CaseMode> for CaseStyle {
    fn from(case: CaseMode) -> Self {
        match case {
            CaseMode::Exact => CaseStyle::Exact,
            CaseMode::Ignore => CaseStyle::Ignore,
            CaseMode::Adaptive => CaseStyle::Adaptive,
        }
    }
}

impl From<CaseStyle> for CaseMode {
    fn from(case: CaseStyle) -> Self {
        match case {
            CaseStyle::Exact => CaseMode::Exact,
            CaseStyle::Ignore => CaseMode::Ignore,
            CaseStyle::Adaptive => CaseMode::Adaptive,
        }
    }
}

impl From<aralo_core::DraftIssue> for DraftProblem {
    fn from(issue: aralo_core::DraftIssue) -> Self {
        use aralo_core::Problem;
        let (message, conflicts_with) = match issue.problem {
            Problem::Blank => (
                "An abbreviation of only spaces can never be typed.".to_owned(),
                None,
            ),
            Problem::Taken { by, name, path } => (
                format!(
                    "“{name}” already answers to this, in {}. Only one of the two will expand.",
                    path.display()
                ),
                Some(by.to_string()),
            ),
            Problem::Repeated => ("The same abbreviation twice.".to_owned(), None),
            Problem::UnsupportedKind(kind) => (
                format!("{kind:?} snippets do not expand in this version yet."),
                None,
            ),
        };
        Self {
            abbreviation: issue.abbr,
            message,
            conflicts_with,
        }
    }
}

impl From<aralo_core::SearchHit> for SearchResult {
    fn from(hit: aralo_core::SearchHit) -> Self {
        use aralo_core::Field;
        Self {
            id: hit.id.to_string(),
            name: hit.name,
            abbreviations: hit.abbr,
            group: hit.group,
            enabled: hit.enabled,
            field: match hit.field {
                Field::Abbreviation => SearchField::Abbreviation,
                Field::Label => SearchField::Label,
                Field::Body => SearchField::Body,
                Field::Tag => SearchField::Tag,
                Field::Group => SearchField::Group,
            },
            text: hit.text,
            matched: hit.matched,
        }
    }
}

impl From<&ImportReport> for ImportSummary {
    fn from(report: &ImportReport) -> Self {
        Self {
            format: report.format.to_string(),
            dry_run: report.dry_run,
            total: report.total() as u32,
            imported: report.imported() as u32,
            needs_edit: report.count(Outcome::NeedsEdit) as u32,
            skipped: report.count(Outcome::Skipped) as u32,
            fidelity: report.fidelity(),
            entries: report
                .entries
                .iter()
                .map(|entry| ImportedSnippet {
                    label: entry.label.clone(),
                    abbreviations: entry.abbr.clone(),
                    group: entry.group.clone(),
                    path: entry
                        .path
                        .as_ref()
                        .map(|path| path.to_string_lossy().into_owned()),
                    outcome: match entry.outcome {
                        Outcome::Clean => ImportOutcome::Clean,
                        Outcome::NeedsEdit => ImportOutcome::NeedsEdit,
                        Outcome::Skipped => ImportOutcome::Skipped,
                    },
                    notes: entry.notes.iter().map(|note| note.detail.clone()).collect(),
                })
                .collect(),
            report: report.to_string(),
        }
    }
}

fn describe(issue: &aralo_core::Issue) -> (DiagnosticLevel, String) {
    use aralo_core::Issue;
    use DiagnosticLevel::{Error, Note, Warning};
    match issue {
        Issue::Unreadable(why) => (Error, format!("Cannot be read: {why}")),
        Issue::Invalid(why) => (Error, why.clone()),
        Issue::TooLarge { bytes } => (Error, format!("{bytes} bytes is too large for a snippet.")),
        Issue::DuplicateId { first } => (
            Error,
            format!(
                "Has the same id as {}, so this file is ignored.",
                first.display()
            ),
        ),
        Issue::AbbreviationRejected {
            abbreviation,
            reason,
        } => (
            Error,
            format!("The abbreviation “{abbreviation}” cannot be used: {reason}."),
        ),
        Issue::TooDeep => (
            Error,
            "Folders are nested too deeply; not loaded.".to_owned(),
        ),
        Issue::SymlinkedFolder => (
            Warning,
            "Symbolic links to folders are not followed.".to_owned(),
        ),
        Issue::UnsupportedKind(kind) => (
            Warning,
            format!("{kind:?} snippets do not expand in this version yet."),
        ),
        Issue::MissingId => (
            Note,
            "Has no id yet; Aralo adds one when it saves the file.".to_owned(),
        ),
        Issue::NotASnippet => (Note, "No front matter, so not a snippet.".to_owned()),
    }
}
