//! The bridge: `aralo-core` as the native shells see it, generated by UniFFI.
//!
//! Two objects cross the bridge. [`Engine`] is the keystroke path: one call per
//! key, one short lock, no file access. [`Core`] is everything else. They share
//! the open library, so a match comes back from `on_key` with its plan already
//! built and the shell never makes a second call while a key is waiting.
//!
//! Nothing here may panic: a panic would cross the bridge as a crash in the
//! process that holds the event tap. Locks recover from poisoning instead.
//!
//! There is no hand-written `unsafe` in this crate. The only `unsafe` is what
//! `uniffi::setup_scaffolding!` generates, which is why this is the one crate
//! that does not forbid it.

use std::path::PathBuf;
use std::sync::{Arc, Mutex, MutexGuard, PoisonError, RwLock, RwLockReadGuard};

use aralo_core::compat;
use aralo_core::engine as matcher;
use aralo_core::snippet::SnippetId;
use aralo_core::{CompatTable, MatchInfo, Step};

uniffi::setup_scaffolding!();

#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum BridgeError {
    #[error("{message}")]
    Library { message: String },
    #[error("{message}")]
    CompatTable { message: String },
}

impl From<aralo_core::CoreError> for BridgeError {
    fn from(error: aralo_core::CoreError) -> Self {
        BridgeError::Library {
            message: error.to_string(),
        }
    }
}

/// A key as the shell saw it, after the keyboard layout and dead keys.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum KeyInput {
    /// A key that produced exactly one Unicode scalar. It crosses the bridge as
    /// a number so that no keystroke ever sits in a heap-allocated string. A
    /// key that produced several is not reported; the shell calls
    /// `reset(UnmappableInput)`. A key that produced none (a dead key on its
    /// own) is not reported at all.
    Char {
        scalar: u32,
    },
    Backspace,
    /// The platform's undo shortcut.
    Undo,
}

/// What the shell does with the key it just reported.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Enum)]
pub enum KeyAction {
    /// Let the key through.
    Pass,
    /// Swallow the key if `consume`, run the steps in order the way `profile`
    /// says, then call `expansion_done` when `undo_delete_count` is present.
    Expand {
        snippet_id: String,
        consume: bool,
        steps: Vec<PlanStep>,
        undo_delete_count: Option<u32>,
        profile: InjectionProfile,
    },
    /// Swallow the key, take the expansion back the way `profile` says
    /// (`delete_count` Backspaces, or one undo shortcut), type `retype`.
    UndoExpansion {
        delete_count: u32,
        retype: String,
        method: InsertMethod,
        profile: InjectionProfile,
    },
}

/// How to insert, delete and undo in the app that has the keyboard; one row of
/// the compatibility table (`data/compat/apps.toml`). The shell follows it and
/// chooses nothing itself.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Record)]
pub struct InjectionProfile {
    pub insert: InsertChoice,
    /// The longest text `Auto` still types, in UTF-16 units.
    pub typing_limit: u32,
    /// Pause after every synthetic key.
    pub key_delay_ms: u32,
    /// How long the app gets to read the pasteboard before it is restored.
    pub paste_settle_ms: u32,
    pub undo: UndoStyle,
    pub delete: DeleteStrategy,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum InsertChoice {
    /// Type short single-line text, paste the rest.
    Auto,
    /// Always type. A line break is a Return key.
    Type,
    /// Always paste.
    Paste,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum UndoStyle {
    /// A pasted expansion is undone with one undo shortcut.
    Native,
    /// Every expansion is undone with Backspace.
    Backspace,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum DeleteStrategy {
    /// One Backspace per character.
    Backspace,
    /// Shift+Left over the characters, then one Backspace.
    Select,
}

/// One step of an expansion plan; see `docs/format/expansion-plan.md`.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Enum)]
pub enum PlanStep {
    Delete { count: u32 },
    InsertText { text: String },
    InsertRich { html: String, plain: String },
    KeyPress { key: PlanKey },
    Delay { millis: u32 },
    MoveCursor { graphemes: u32, select: bool },
}

/// One app the compatibility table names, with its row resolved.
#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct CompatApp {
    pub name: String,
    pub bundle_id: String,
    pub profile: InjectionProfile,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum PlanKey {
    Return,
    Tab,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum InsertMethod {
    Typed,
    Pasted,
}

/// Why the shell is clearing the buffer. Every reason zeroes it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum ResetReason {
    MouseDown,
    Navigation,
    Shortcut,
    AppSwitch,
    FocusChange,
    SecureInput,
    InputMethod,
    UnmappableInput,
    Manual,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct SnippetSummary {
    pub id: String,
    pub label: String,
    pub abbreviations: Vec<String>,
    /// Folder names from the library root down to the snippet's group.
    pub group: Vec<String>,
    /// Path from the library root.
    pub path: String,
    pub enabled: bool,
    /// The start of the body, for a list row.
    pub preview: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, uniffi::Enum)]
pub enum DiagnosticLevel {
    Error,
    Warning,
    Note,
}

#[derive(Debug, Clone, PartialEq, Eq, uniffi::Record)]
pub struct LibraryDiagnostic {
    /// Path from the library root.
    pub path: String,
    pub level: DiagnosticLevel,
    pub message: String,
}

/// The library both objects share. Swapped whole on reload, so the keystroke
/// path only ever waits for a pointer swap, never for the disk.
struct Shared {
    library: RwLock<aralo_core::Core>,
    compat: RwLock<CompatTable>,
}

impl Shared {
    fn library(&self) -> RwLockReadGuard<'_, aralo_core::Core> {
        self.library.read().unwrap_or_else(PoisonError::into_inner)
    }

    fn compat(&self) -> RwLockReadGuard<'_, CompatTable> {
        self.compat.read().unwrap_or_else(PoisonError::into_inner)
    }
}

/// The app that receives keys, and its row of the compatibility table. Looked
/// up when the app changes, so a match only has to copy it.
struct FrontApp {
    bundle_id: String,
    profile: compat::InjectionProfile,
}

/// The keystroke path.
#[derive(uniffi::Object)]
pub struct Engine {
    matcher: Mutex<matcher::Engine>,
    front_app: Mutex<FrontApp>,
    shared: Arc<Shared>,
}

impl std::fmt::Debug for Engine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Engine").finish_non_exhaustive()
    }
}

impl Engine {
    fn matcher(&self) -> MutexGuard<'_, matcher::Engine> {
        self.matcher.lock().unwrap_or_else(PoisonError::into_inner)
    }

    fn front_app(&self) -> MutexGuard<'_, FrontApp> {
        self.front_app
            .lock()
            .unwrap_or_else(PoisonError::into_inner)
    }

    /// Not taken on the way in: only a match or an undo needs it.
    fn profile(&self) -> InjectionProfile {
        self.front_app().profile.into()
    }

    /// Looks the front app up again, after the table changed.
    fn refresh_profile(&self) {
        let mut front_app = self.front_app();
        front_app.profile = self.shared.compat().profile_for(&front_app.bundle_id);
    }
}

#[uniffi::export]
impl Engine {
    pub fn on_key(&self, key: KeyInput) -> KeyAction {
        let event = match key {
            KeyInput::Char { scalar } => match char::from_u32(scalar) {
                Some(c) => matcher::KeyEvent::Char(c),
                None => {
                    self.matcher().reset(matcher::ResetReason::UnmappableInput);
                    return KeyAction::Pass;
                }
            },
            KeyInput::Backspace => matcher::KeyEvent::Backspace,
            KeyInput::Undo => matcher::KeyEvent::Undo,
        };
        // The engine lock is released before the plan is built.
        let verdict = self.matcher().on_key(event);
        match verdict {
            matcher::KeyVerdict::Pass => KeyAction::Pass,
            matcher::KeyVerdict::Match {
                snippet_id,
                delete_count,
                consume,
                case,
                trailing,
            } => {
                let expansion = self.shared.library().expand(MatchInfo {
                    snippet_id,
                    delete_count,
                    case,
                    trailing,
                });
                match expansion {
                    Some(expansion) => KeyAction::Expand {
                        snippet_id: SnippetId::from_u128(snippet_id.0).to_string(),
                        consume,
                        steps: expansion
                            .plan
                            .steps
                            .into_iter()
                            .map(PlanStep::from)
                            .collect(),
                        undo_delete_count: expansion.undo_delete_count,
                        profile: self.profile(),
                    },
                    // The snippet went away between the snapshot and now.
                    None => KeyAction::Pass,
                }
            }
            matcher::KeyVerdict::UndoLast {
                delete_count,
                retype,
                method,
            } => KeyAction::UndoExpansion {
                delete_count,
                retype,
                method: match method {
                    matcher::InsertMethod::Typed => InsertMethod::Typed,
                    matcher::InsertMethod::Pasted => InsertMethod::Pasted,
                },
                profile: self.profile(),
            },
        }
    }

    /// Arms undo for the expansion that `on_key` just returned.
    pub fn expansion_done(&self, snippet_id: String, delete_count: u32, method: InsertMethod) {
        let Ok(id) = snippet_id.parse::<SnippetId>() else {
            return;
        };
        self.matcher().expansion_done(matcher::ExpansionRecord {
            snippet_id: matcher::SnippetId(id.as_u128()),
            delete_count,
            method: match method {
                InsertMethod::Typed => matcher::InsertMethod::Typed,
                InsertMethod::Pasted => matcher::InsertMethod::Pasted,
            },
        });
    }

    pub fn reset(&self, reason: ResetReason) {
        self.matcher().reset(match reason {
            ResetReason::MouseDown => matcher::ResetReason::MouseDown,
            ResetReason::Navigation => matcher::ResetReason::Navigation,
            ResetReason::Shortcut => matcher::ResetReason::Shortcut,
            ResetReason::AppSwitch => matcher::ResetReason::AppSwitch,
            ResetReason::FocusChange => matcher::ResetReason::FocusChange,
            ResetReason::SecureInput => matcher::ResetReason::SecureInput,
            ResetReason::InputMethod => matcher::ResetReason::InputMethod,
            ResetReason::UnmappableInput => matcher::ResetReason::UnmappableInput,
            ResetReason::Manual => matcher::ResetReason::Manual,
        });
    }

    /// The bundle ID of the app that now receives keys.
    pub fn set_front_app(&self, bundle_id: String) {
        self.matcher().set_front_app(&bundle_id);
        let profile = self.shared.compat().profile_for(&bundle_id);
        *self.front_app() = FrontApp { bundle_id, profile };
    }

    /// How text goes into the app that has the keyboard now.
    pub fn injection_profile(&self) -> InjectionProfile {
        self.profile()
    }

    pub fn set_paused(&self, paused: bool) {
        self.matcher().set_paused(paused);
    }

    pub fn is_paused(&self) -> bool {
        self.matcher().is_paused()
    }

    /// Apps the user excluded. The built-in presets (password managers) stay
    /// excluded as well: the engine's own call replaces the whole list, and a
    /// shell that forgot to pass the presets along would silently drop them.
    pub fn set_excluded_apps(&self, mut bundle_ids: Vec<String>) {
        bundle_ids.extend(excluded_app_presets());
        self.matcher().set_excluded_apps(bundle_ids);
    }

    /// True when the buffer holds nothing. For the privacy self-test.
    pub fn holds_no_keystrokes(&self) -> bool {
        self.matcher().holds_no_keystrokes()
    }
}

/// The open library.
#[derive(uniffi::Object)]
pub struct Core {
    shared: Arc<Shared>,
    engine: Arc<Engine>,
}

impl std::fmt::Debug for Core {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Core").finish_non_exhaustive()
    }
}

#[uniffi::export]
impl Core {
    /// Opens the library folder, creating it (with the starter snippets) when
    /// it does not exist yet.
    #[uniffi::constructor]
    pub fn open_library(path: String) -> Result<Arc<Self>, BridgeError> {
        let library = aralo_core::Core::open(&PathBuf::from(path))?;
        let matcher = library.engine();
        let compat = CompatTable::bundled();
        let front_app = FrontApp {
            bundle_id: String::new(),
            profile: compat.defaults(),
        };
        let shared = Arc::new(Shared {
            library: RwLock::new(library),
            compat: RwLock::new(compat),
        });
        let engine = Arc::new(Engine {
            matcher: Mutex::new(matcher),
            front_app: Mutex::new(front_app),
            shared: Arc::clone(&shared),
        });
        Ok(Arc::new(Self { shared, engine }))
    }

    /// The engine for this library. There is one; every call returns it.
    pub fn engine(&self) -> Arc<Engine> {
        Arc::clone(&self.engine)
    }

    /// Reads the folder again and hands the engine the new snapshot. On
    /// failure the library that was loaded stays in use.
    pub fn reload(&self) -> Result<(), BridgeError> {
        let root = self.shared.library().root().to_owned();
        // Disk work happens with no lock held.
        let fresh = aralo_core::Core::open_read_only(&root)?;
        let snapshot = fresh.snapshot();
        *self
            .shared
            .library
            .write()
            .unwrap_or_else(PoisonError::into_inner) = fresh;
        self.engine.matcher().set_snapshot(snapshot);
        Ok(())
    }

    /// Replaces the built-in compatibility table with the file at `path`, for
    /// trying an app's settings without rebuilding the core. A file that does
    /// not parse changes nothing.
    pub fn load_compat_table(&self, path: String) -> Result<(), BridgeError> {
        let table = read_compat_table(&path)?;
        *self
            .shared
            .compat
            .write()
            .unwrap_or_else(PoisonError::into_inner) = table;
        self.engine.refresh_profile();
        Ok(())
    }

    pub fn library_path(&self) -> String {
        self.shared.library().root().to_string_lossy().into_owned()
    }

    pub fn snippets(&self) -> Vec<SnippetSummary> {
        self.shared
            .library()
            .snippets()
            .iter()
            .map(|snippet| SnippetSummary {
                id: snippet.id.to_string(),
                label: snippet.file.front.label.clone(),
                abbreviations: snippet.file.front.abbr.clone(),
                group: snippet.group.clone(),
                path: snippet.path.to_string_lossy().into_owned(),
                enabled: snippet.settings.enabled,
                preview: snippet.file.body.chars().take(PREVIEW_CHARS).collect(),
            })
            .collect()
    }

    pub fn diagnostics(&self) -> Vec<LibraryDiagnostic> {
        self.shared
            .library()
            .diagnostics()
            .map(|diagnostic| {
                let (level, message) = describe(&diagnostic.issue);
                LibraryDiagnostic {
                    path: diagnostic.path.to_string_lossy().into_owned(),
                    level,
                    message,
                }
            })
            .collect()
    }
}

const PREVIEW_CHARS: usize = 120;

/// The version of the Rust core, for the About window and bug reports.
#[uniffi::export]
pub fn core_version() -> String {
    env!("CARGO_PKG_VERSION").to_owned()
}

/// Apps Aralo stays out of without being told to, for the settings window.
#[uniffi::export]
pub fn excluded_app_presets() -> Vec<String> {
    matcher::EXCLUDED_APP_PRESETS
        .iter()
        .map(|id| (*id).to_owned())
        .collect()
}

/// The apps a compatibility table names, in file order: the table built into
/// the core, or the file at `path`. The injection matrix walks this list, so
/// it tests the apps the table makes claims about.
#[uniffi::export]
pub fn compat_apps(path: Option<String>) -> Result<Vec<CompatApp>, BridgeError> {
    let table = match path {
        Some(path) => read_compat_table(&path)?,
        None => CompatTable::bundled(),
    };
    Ok(table
        .apps()
        .iter()
        .map(|app| CompatApp {
            name: app.name.clone(),
            bundle_id: app.bundle_id.clone(),
            profile: app.profile.into(),
        })
        .collect())
}

fn read_compat_table(path: &str) -> Result<CompatTable, BridgeError> {
    let text = std::fs::read_to_string(path).map_err(|error| BridgeError::CompatTable {
        message: format!("cannot read {path}: {error}"),
    })?;
    CompatTable::parse(&text).map_err(|error| BridgeError::CompatTable {
        message: format!("{path}: {error}"),
    })
}

impl From<compat::InjectionProfile> for InjectionProfile {
    fn from(profile: compat::InjectionProfile) -> Self {
        Self {
            insert: match profile.insert {
                compat::InsertChoice::Auto => InsertChoice::Auto,
                compat::InsertChoice::Type => InsertChoice::Type,
                compat::InsertChoice::Paste => InsertChoice::Paste,
            },
            typing_limit: profile.typing_limit,
            key_delay_ms: profile.key_delay_ms,
            paste_settle_ms: profile.paste_settle_ms,
            undo: match profile.undo {
                compat::UndoStyle::Native => UndoStyle::Native,
                compat::UndoStyle::Backspace => UndoStyle::Backspace,
            },
            delete: match profile.delete {
                compat::DeleteStrategy::Backspace => DeleteStrategy::Backspace,
                compat::DeleteStrategy::Select => DeleteStrategy::Select,
            },
        }
    }
}

impl From<Step> for PlanStep {
    fn from(step: Step) -> Self {
        match step {
            Step::Delete { count } => PlanStep::Delete { count },
            Step::InsertText { text } => PlanStep::InsertText { text },
            Step::InsertRich { html, plain } => PlanStep::InsertRich { html, plain },
            Step::KeyPress { key } => PlanStep::KeyPress {
                key: match key {
                    aralo_core::Key::Return => PlanKey::Return,
                    aralo_core::Key::Tab => PlanKey::Tab,
                },
            },
            Step::Delay { millis } => PlanStep::Delay { millis },
            Step::MoveCursor { graphemes, select } => PlanStep::MoveCursor { graphemes, select },
        }
    }
}

fn describe(issue: &aralo_core::Issue) -> (DiagnosticLevel, String) {
    use aralo_core::Issue;
    use DiagnosticLevel::{Error, Note, Warning};
    match issue {
        Issue::Unreadable(why) => (Error, format!("Cannot be read: {why}")),
        Issue::Invalid(why) => (Error, why.clone()),
        Issue::TooLarge { bytes } => (Error, format!("{bytes} bytes is too large for a snippet.")),
        Issue::DuplicateId { first } => (
            Error,
            format!(
                "Has the same id as {}, so this file is ignored.",
                first.display()
            ),
        ),
        Issue::AbbreviationRejected {
            abbreviation,
            reason,
        } => (
            Error,
            format!("The abbreviation “{abbreviation}” cannot be used: {reason}."),
        ),
        Issue::TooDeep => (
            Error,
            "Folders are nested too deeply; not loaded.".to_owned(),
        ),
        Issue::SymlinkedFolder => (
            Warning,
            "Symbolic links to folders are not followed.".to_owned(),
        ),
        Issue::UnsupportedKind(kind) => (
            Warning,
            format!("{kind:?} snippets do not expand in this version yet."),
        ),
        Issue::MissingId => (
            Note,
            "Has no id yet; Aralo adds one when it saves the file.".to_owned(),
        ),
        Issue::NotASnippet => (Note, "No front matter, so not a snippet.".to_owned()),
    }
}
