#!/usr/bin/env bash
# Builds what the Swift shell links against, all from crates/aralo-ffi:
#
#   apps/macos/Generated/AraloBridge/            a Swift package
#     Package.swift
#     AraloFFI.xcframework/                      the Rust core, as a static library
#     Sources/AraloBridge/aralo_ffi.swift        the UniFFI Swift bindings
#
# Everything under apps/macos/Generated is output. Never edit it; run this again.
#
# Usage: scripts/build-xcframework.sh [--debug]
#
# The library is universal (arm64 + x86_64, ADR-0010) when both Rust targets
# are installed. With one target, as with a Homebrew Rust, it builds that one
# and says so. Set ARALO_TARGETS to choose: ARALO_TARGETS="aarch64-apple-darwin".
set -euo pipefail

profile=release
profile_flag=(--release)
if [[ "${1:-}" == "--debug" ]]; then
    profile=debug
    profile_flag=()
fi

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

if [[ "$(uname -s)" != "Darwin" ]]; then
    echo "error: the XCFramework can only be built on macOS" >&2
    exit 1
fi

lib=libaralo_ffi
out="$root/apps/macos/Generated/AraloBridge"
work="$root/target/xcframework"
target_dir="${CARGO_TARGET_DIR:-$root/target}"

host="$(rustc -vV | sed -n 's/^host: //p')"
if [[ -n "${ARALO_TARGETS:-}" ]]; then
    read -r -a targets <<<"$ARALO_TARGETS"
else
    targets=("$host")
    sysroot="$(rustc --print sysroot)"
    for candidate in aarch64-apple-darwin x86_64-apple-darwin; do
        if [[ "$candidate" != "$host" && -d "$sysroot/lib/rustlib/$candidate/lib" ]]; then
            targets+=("$candidate")
        fi
    done
fi
if [[ ${#targets[@]} -eq 1 ]]; then
    echo "note: building for ${targets[0]} only; install the other Apple target for a universal library" >&2
fi

# The deployment target must match apps/macos/project.yml.
export MACOSX_DEPLOYMENT_TARGET="${MACOSX_DEPLOYMENT_TARGET:-14.0}"

archives=()
for target in "${targets[@]}"; do
    echo "==> cargo build ($target, $profile)"
    # The ${x[@]+...} form is for bash 3.2, which macOS ships: with `set -u` it
    # treats an empty array as unbound.
    cargo build -p aralo-ffi --lib ${profile_flag[@]+"${profile_flag[@]}"} --target "$target"
    archives+=("$target_dir/$target/$profile/$lib.a")
done

rm -rf "$work"
mkdir -p "$work/headers" "$work/swift"

echo "==> uniffi-bindgen"
cargo run --quiet -p aralo-ffi --features bindgen --bin uniffi-bindgen -- \
    generate "$target_dir/${targets[0]}/$profile/$lib.dylib" \
    --language swift --no-format --out-dir "$work/swift"

# An XCFramework wants its module map to be called module.modulemap.
cp "$work/swift/aralo_ffiFFI.h" "$work/headers/"
cp "$work/swift/aralo_ffiFFI.modulemap" "$work/headers/module.modulemap"

if [[ ${#archives[@]} -gt 1 ]]; then
    echo "==> lipo"
    lipo -create "${archives[@]}" -output "$work/$lib.a"
else
    cp "${archives[0]}" "$work/$lib.a"
fi

echo "==> xcodebuild -create-xcframework"
rm -rf "$out"
mkdir -p "$out/Sources/AraloBridge"
xcodebuild -create-xcframework \
    -library "$work/$lib.a" -headers "$work/headers" \
    -output "$out/AraloFFI.xcframework" >/dev/null

cp "$work/swift/aralo_ffi.swift" "$out/Sources/AraloBridge/"

cat >"$out/Package.swift" <<'PACKAGE'
// swift-tools-version: 5.10
// Generated by scripts/build-xcframework.sh. Do not edit.
import PackageDescription

let package = Package(
    name: "AraloBridge",
    platforms: [.macOS(.v14)],
    products: [.library(name: "AraloBridge", targets: ["AraloBridge"])],
    targets: [
        .binaryTarget(name: "AraloFFI", path: "AraloFFI.xcframework"),
        .target(name: "AraloBridge", dependencies: ["AraloFFI"]),
    ]
)
PACKAGE

echo "==> $out"
lipo -info "$work/$lib.a"
