import AppKit

/// Everything on the pasteboard: one dictionary of type to data per item.
public typealias PasteboardContents = [[String: Data]]

/// The pasteboard as the injector uses it. Tests use a fake.
public protocol PasteboardAccess: AnyObject {
    var changeCount: Int { get }
    func contents() -> PasteboardContents
    /// Replaces the contents with `text`, plus empty entries for `markerTypes`.
    func write(text: String, markerTypes: [String])
    func restore(_ contents: PasteboardContents)
}

public extension PasteboardAccess {
    /// The plain text on the pasteboard, which is what a `{{clipboard}}`
    /// placeholder is worth.
    ///
    /// Nil when nothing on it is text: a copied image expands to nothing, and
    /// the placeholder stays empty rather than describing what it found.
    func text() -> String? {
        let plain = NSPasteboard.PasteboardType.string.rawValue
        for item in contents() {
            if let data = item[plain], let text = String(data: data, encoding: .utf8) {
                return text
            }
        }
        return nil
    }
}

public enum PasteboardMarker {
    /// The nspasteboard.org types that tell clipboard managers to skip an entry.
    public static let all = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]
}

public final class SystemPasteboard: PasteboardAccess {
    private let pasteboard: NSPasteboard

    public init(_ pasteboard: NSPasteboard = .general) {
        self.pasteboard = pasteboard
    }

    public var changeCount: Int { pasteboard.changeCount }

    public func contents() -> PasteboardContents {
        (pasteboard.pasteboardItems ?? []).map { item in
            var entry: [String: Data] = [:]
            for type in item.types {
                entry[type.rawValue] = item.data(forType: type)
            }
            return entry
        }
    }

    public func write(text: String, markerTypes: [String]) {
        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        for marker in markerTypes {
            item.setData(Data(), forType: NSPasteboard.PasteboardType(marker))
        }
        pasteboard.writeObjects([item])
    }

    public func restore(_ contents: PasteboardContents) {
        pasteboard.clearContents()
        let items = contents.map { entry in
            let item = NSPasteboardItem()
            for (type, data) in entry {
                item.setData(data, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
    }
}
